name: Build & Publish Release APK

on:
  push:
    # branches: ["master"]

    # tags:
    #   - "*"

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build apk
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          ruby-version: "3.3.0" # This is only set because there is some random issues with the default ruby version. See https://github.com/fastlane/fastlane/issues/21942
          output-path: coinsaw-xxx.apk
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: xxx
          draft: true
          title: xxx
          files: |
            coinsaw-xxx.apk
